"""make_text_graphics.py: draw every TEXT record (readable words in the picture) as a text graphic, and run the
command graphics.

In plain words:
- readable words are never generated by a video model; each one is drawn here and laid over the finished clip after
  any flip (blueprint 8.5, route d; K17; D12 rules 22 and 25);
- each TEXT is drawn as an SVG file reading normally and, for words that belong to the story world, a second copy
  mirrored, because a shot in the mirror world may need the reversed words (the orientation of each shot comes from
  derive_fields.text_orientation); title cards and captions are never mirrored (D12 rule 17);
- sizes, fonts and colours come from adapters/phrasebook.json, "text_graphics" (D12 Recipe 7 and rules 6-7): the
  title card is IBM Plex Sans Medium in capitals, off-white on black, capitals 6% of the picture height; words the
  audience must read have capitals at least 4% of the picture height;
- the mirrored copy wraps the drawing in translate(width, 0) scale(-1, 1), because a bare scale(-1, 1) leaves a
  blank picture (C2 R6);
- a PNG copy of each SVG is made when a converter is installed (rsvg-convert, resvg, inkscape or magick);
- a page, "Text graphics.md", lists every graphic with its reading time (K09, the text_floor constant; doubled when
  mirrored), the shots it is in, the file each shot uses, and the fonts with their licences (D4).

Command: graphics [--text <TEXT IDs>] [--scene <scene IDs>] [--no-png]. Exit 0: drawn; 1: a shot shows a text for
less time than it takes to read; 2: could not run.
Standard library only.
"""

import json
import re
import shutil
import subprocess
from pathlib import Path
from xml.sax.saxutils import escape

from .derive_fields import (Breakdown, number_of, scene_label, shot_number, text_orientation, text_reading_seconds)
from .record_format import SKILL_FOLDER, normalise_word, split_item, split_list

PACK_FOLDER = "20 Prompts for AI video"
GRAPHICS_FOLDER = "Text graphics"
PAGE_NAME = "Text graphics.md"

# kinds of TEXT (schema TEXT.kind) and the phrasebook style that draws them
SCREEN_KINDS = ("screen", "visor", "wrist", "monitor", "timestamp")
NEVER_MIRRORED_DEFAULT = ("title_card", "caption")

# average advance of one letter, as a share of the font size, for wrapping lines (a safe over-estimate for sans
# faces; the exact width is the renderer's)
UPPER_ADVANCE = 0.66
LOWER_ADVANCE = 0.54
LINE_GAP = 1.3

CONVERTERS = (
    ("rsvg-convert", lambda svg, png: ["rsvg-convert", "-o", str(png), str(svg)]),
    ("resvg", lambda svg, png: ["resvg", str(svg), str(png)]),
    ("inkscape", lambda svg, png: ["inkscape", str(svg), "--export-type=png", f"--export-filename={png}"]),
    ("magick", lambda svg, png: ["magick", "-background", "none", str(svg), str(png)]),
)


def load_phrasebook(skill_folder=None):
    path = Path(skill_folder or SKILL_FOLDER) / "adapters" / "phrasebook.json"
    if not path.is_file():
        return {}
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def is_none(value):
    return value is None or str(value).strip().lower() in ("", "none", "-", "n/a")


def three_digits(identifier):
    """A shot's number as the views say it ("110"); an ID that is not well formed (FORM-02 reports it) as written."""
    number = shot_number(identifier)
    return f"{number:03d}" if number is not None else str(identifier)


def plain_file_name(text):
    """A file name from a record's title: characters that no system allows are taken out."""
    name = re.sub(r'[\\/:*?"<>|]+', "", str(text or "")).strip().rstrip(".")
    return re.sub(r"\s+", " ", name) or "text"


class TextGraphic:
    """One TEXT drawn: its style, sizes, lines, file names, and the shots that show it."""

    def __init__(self, breakdown, record, settings, frame_shape):
        self.record = record
        self.identifier = record.identifier
        self.kind = normalise_word(record.get("kind") or "sign")
        self.words = str(record.get("words") or "").strip().strip('"“”')
        self.settings = settings
        never = settings.get("never_mirrored") or list(NEVER_MIRRORED_DEFAULT)
        self.mirrorable = self.kind not in never
        self.style_name = ("title_card" if self.kind in ("title_card", "caption")
                           else "screen" if self.kind in SCREEN_KINDS else "sign")
        self.style = dict(settings.get(self.style_name) or {})
        canvas = (settings.get("canvas") or {}).get(frame_shape) or (settings.get("canvas") or {}).get("16_9") or [1920, 1080]
        self.width, self.height = int(canvas[0]), int(canvas[1])
        self.frame_shape = frame_shape
        self.method = normalise_word(record.get("method") or "composite")
        self.animated = not is_none(record.get("animation"))
        self.title = plain_file_name(record.title or self.words[:40])
        self.notes = []
        self.shots = []
        self.layout()

    def must_read(self):
        emphasis = number_of(self.record.get("emphasis"), 0) or 0
        return normalise_word(self.record.get("plot_critical") or "") == "yes" or emphasis >= 2

    def cap_share(self):
        """Capital height as a share of the picture height (D12 rules 6-7)."""
        style_share = float(self.style.get("cap_share") or 0.04)
        if self.kind == "title_card":
            return style_share
        if self.kind == "caption":
            return float(self.settings.get("must_read_cap_share") or 0.04)
        if self.must_read():
            return max(style_share, float(self.settings.get("must_read_cap_share") or 0.04))
        return float(self.settings.get("secondary_cap_share") or 0.025)

    def layout(self):
        font = self.style.get("font") or "IBM Plex Sans"
        cap_per_em = float((self.settings.get("cap_height_per_em") or {}).get(font) or 0.7)
        cap = round(self.cap_share() * self.height)
        self.font = font
        self.weight = int(self.style.get("weight") or 500)
        self.font_size = round(cap / cap_per_em)
        self.cap = cap
        spacing_share = float(self.style.get("letter_spacing_share_of_em") or 0.0)
        self.letter_spacing = round(self.font_size * spacing_share, 1)
        text = self.words.upper() if normalise_word(self.style.get("case") or "") == "upper" else self.words
        margin = float(self.settings.get("safe_area_margin_share") or 0.05)
        usable = self.width * (1 - 2 * margin)
        self.lines = self.wrap(text, usable)
        widest = max((self.line_width(line) for line in self.lines), default=0)
        if widest > usable:
            shrink = usable / widest
            self.font_size = max(1, int(self.font_size * shrink))
            self.cap = round(self.font_size * cap_per_em)
            self.letter_spacing = round(self.font_size * spacing_share, 1)
            self.notes.append(f"one word is too long for the safe area at the planned size, so the letters were made "
                              f"smaller: capitals {self.cap} pixels high instead of {cap}")

    def line_width(self, line):
        width = 0.0
        for letter in line:
            width += (UPPER_ADVANCE if letter.isupper() or letter.isdigit() else LOWER_ADVANCE) * self.font_size
            width += self.letter_spacing
        return width

    def wrap(self, text, usable):
        """Lines that fit the safe area: the writer's own line breaks first, then word by word."""
        lines = []
        for paragraph in [part.strip() for part in re.split(r"\s*(?:\n|\|)\s*", text) if part.strip()]:
            current = ""
            for word in paragraph.split():
                trial = f"{current} {word}".strip()
                if current and self.line_width(trial) > usable:
                    lines.append(current)
                    current = word
                else:
                    current = trial
            if current:
                lines.append(current)
        return lines or [text]

    def svg(self, mirrored=False):
        """The SVG text of this graphic, reading normally or mirrored."""
        width, height = self.width, self.height
        middle = height / 2
        if self.kind == "title_card":
            middle -= 0.02 * height   # optically centred about 2% above the middle (D12 Recipe 7)
        gap = self.font_size * LINE_GAP
        count = len(self.lines)
        first_baseline = middle + self.cap / 2 - gap * (count - 1) / 2
        colour = self.style.get("colour") or "#E8E6DF"
        background = self.style.get("background") or "transparent"
        parts = ['<?xml version="1.0" encoding="UTF-8"?>',
                 f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">']
        if background and background != "transparent":
            parts.append(f'  <rect x="0" y="0" width="{width}" height="{height}" fill="{escape(background)}"/>')
        if mirrored:
            parts.append(f'  <g transform="translate({width},0) scale(-1,1)">')
        indent = "    " if mirrored else "  "
        for index, line in enumerate(self.lines):
            baseline = round(first_baseline + index * gap)
            spacing = f' letter-spacing="{self.letter_spacing:g}"' if self.letter_spacing else ""
            parts.append(f'{indent}<text x="{width / 2:g}" y="{baseline:g}" font-family="{escape(self.font)}" '
                         f'font-weight="{self.weight}" font-size="{self.font_size}"{spacing} fill="{escape(colour)}" '
                         f'text-anchor="middle">{escape(line)}</text>')
        if mirrored:
            parts.append("  </g>")
        parts.append("</svg>")
        return "\n".join(parts) + "\n"

    def file_names(self):
        names = {"normal": f"{self.title}.svg"}
        if self.mirrorable:
            names["mirrored"] = f"{self.title} - mirrored.svg"
        return names


def texts_wanted(breakdown, wanted_texts=None, wanted_scenes=None):
    """The TEXT records to draw: all of them, or those named, or those shown in the scenes named."""
    records = [record for record in breakdown.records_of("TEXT")]
    if wanted_texts:
        wanted = set(wanted_texts)
        records = [record for record in records if record.identifier in wanted]
    if wanted_scenes:
        shown = set()
        for scene in wanted_scenes:
            for shot in breakdown.shots_of(scene):
                shown.update(texts_of_shot(shot))
        records = [record for record in records if record.identifier in shown]
    return records


def texts_of_shot(shot):
    """The TEXT IDs a shot shows: its text field and any TX- thing (the same as compile_prompts.text_in_frame)."""
    found = [identifier.strip() for identifier in split_list(shot.get("text") or "") if not is_none(identifier)]
    for written in shot.get_all("thing"):
        first = (split_item(written).first or "").strip()
        if first.startswith("TX-"):
            found.append(first)
    return sorted(set(found))


def shots_showing(breakdown, graphic):
    """[(shot, orientation, seconds on screen, seconds to read)] for every shot that shows this text."""
    found = []
    for scene in breakdown.scene_identifiers():
        for shot in breakdown.shots_of(scene):
            if graphic.identifier not in texts_of_shot(shot):
                continue
            orientation = text_orientation(breakdown, graphic.identifier, shot) or "normal"
            if not graphic.mirrorable:
                orientation = "normal"
            seconds, how = text_reading_seconds(breakdown, graphic.record, orientation == "mirrored")
            found.append((shot, orientation, number_of(shot.get("screen_time"), 0) or 0, seconds, how))
    return found


def converter():
    for name, command in CONVERTERS:
        if shutil.which(name):
            return name, command
    return None, None


def installed_fonts():
    """The font families installed on this computer, or None when that cannot be asked (no fc-list)."""
    if not shutil.which("fc-list"):
        return None
    try:
        result = subprocess.run(["fc-list", ":", "family"], capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    families = set()
    for line in result.stdout.splitlines():
        for family in line.split(","):
            families.add(family.strip().lower())
    return families


def seconds_words(value):
    text = f"{value:.1f}".rstrip("0").rstrip(".")
    return f"{text} second" + ("" if text == "1" else "s")


def graphics_page(breakdown, graphics, settings, png_note, font_notes):
    lines = ["# Text graphics", "",
             "Readable words are never made by a video model. Each one is drawn here and laid over the finished clip "
             "after any flip. The model is told to show a plain, unmarked surface where the words go.", "",
             "Never change a graphic here: change the text in the breakdown and run the graphics command again.", ""]
    if png_note:
        lines += [png_note, ""]
    for graphic in graphics:
        lines += [f"## {graphic.title}", ""]
        lines.append(f"Words: \"{graphic.words}\"")
        kind = graphic.kind.replace("_", " ")
        lines.append(f"Kind: {kind}; lettering: {graphic.font}, weight {graphic.weight}, capitals {graphic.cap} pixels "
                     f"high on a {graphic.width} x {graphic.height} picture ({graphic.cap / graphic.height:.1%} of its height).")
        lettering = graphic.record.get("lettering")
        if not is_none(lettering):
            lines.append(f"The lettering the breakdown asks for: {lettering}. If it differs from the drawing, change the "
                         "style in the phrasebook or finish the graphic by hand from this drawing.")
        files = graphic.file_names()
        lines.append("Files: " + ", ".join(f"{GRAPHICS_FOLDER}/{name}" for name in files.values())
                     + (" (and a PNG of each)" if graphic.png_made else "") + ".")
        if not graphic.mirrorable:
            lines.append("Never mirrored: it belongs to the audience, not to the story world.")
        normal, _ = text_reading_seconds(breakdown, graphic.record, False)
        reading = f"Reading time: {seconds_words(normal)}"
        if graphic.mirrorable:
            doubled, _ = text_reading_seconds(breakdown, graphic.record, True)
            reading += f"; {seconds_words(doubled)} when it reads mirrored"
        lines.append(reading + ".")
        if graphic.animated:
            lines.append(f"It moves ({graphic.record.get('animation')}): this drawing is its first state only; the moving "
                         "version is drawn frame by frame from the style guide.")
        if graphic.method == "background_blur":
            lines.append("Method background blur: it is laid in soft, never read, so the reading time does not apply.")
        if graphic.shots:
            lines += ["", "Shots:"]
            for shot, orientation, on_screen, seconds, _ in graphic.shots:
                use = files["mirrored"] if orientation == "mirrored" and "mirrored" in files else files["normal"]
                where = scene_label(breakdown, shot.identifier.split("-")[0])
                short = on_screen + 1e-9 < seconds and graphic.method != "background_blur"
                lines.append(f"- {where}, shot {three_digits(shot.identifier)}: reads {orientation}, use {use}; on screen "
                             f"{seconds_words(on_screen)}, reading needs {seconds_words(seconds)}"
                             + (": too short, lengthen the shot or hold the words over the next shot" if short else "") + ".")
        else:
            lines += ["", "No shot shows it yet."]
        for note in graphic.notes:
            lines.append(f"Note: {note}.")
        lines.append("")
    fonts = settings.get("fonts") or {}
    used = sorted({graphic.font for graphic in graphics})
    if used:
        lines += ["## Fonts", ""]
        for font in used:
            facts = fonts.get(font) or {}
            licence = {"ofl_1_1": "SIL Open Font License 1.1 (free to use in a film)"}.get(facts.get("licence"), facts.get("licence") or "check its licence")
            lines.append(f"- {font}: {licence}; get it from {facts.get('where', 'its maker')}. Record it as a font in "
                         "22 Rights and credits.")
        lines += font_notes
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def add_graphics_arguments(parser):
    parser.add_argument("--text", help="only these texts: TEXT IDs, comma separated (TX-GOODS-ONLY)")
    parser.add_argument("--scene", help="only the texts shown in these scenes: scene IDs, comma separated")
    parser.add_argument("--no-png", action="store_true", help="write the SVG files only")


def run_graphics(context):
    """stage.py graphics: draw the text graphics of the TEXT records."""
    from .project_files import Project, StageStop
    arguments = context.arguments
    folder = Path(context.project)
    phrasebook = load_phrasebook(context.skill_folder)
    settings = phrasebook.get("text_graphics") or {}
    if not settings:
        raise StageStop("The text graphic styles (adapters/phrasebook.json) are missing from the tools. Use a complete "
                        "copy of the skill folder.")
    breakdown = Breakdown.from_project(folder, context.schema, context.words, context.constants)
    project_record = breakdown.project
    frame_shape = normalise_word(project_record.get("frame_shape") if project_record is not None else "") or "16_9"
    frame_shape = frame_shape.replace(":", "_")
    wanted_texts = [part.strip() for part in (arguments.text or "").split(",") if part.strip()] if getattr(arguments, "text", None) else None
    wanted_scenes = [part.strip() for part in (arguments.scene or "").split(",") if part.strip()] if getattr(arguments, "scene", None) else None
    if wanted_texts:
        known = {record.identifier for record in breakdown.records_of("TEXT")}
        unknown = [identifier for identifier in wanted_texts if identifier not in known]
        if unknown:
            raise StageStop(f"No text in picture with the ID {', '.join(unknown)}. Check the IDs in 08 Places and things.")
    records = texts_wanted(breakdown, wanted_texts, wanted_scenes)
    if not records:
        context.say("No text in picture to draw (no TEXT records" + (" in these scenes" if wanted_scenes else "") + ").")
        context.summary = "graphics: 0 texts"
        return 0
    graphics = []
    for record in records:
        graphic = TextGraphic(breakdown, record, settings, frame_shape)
        graphic.shots = shots_showing(breakdown, graphic)
        graphic.png_made = False
        graphics.append(graphic)
    project = Project(folder, context.schema, context.words)
    output = folder / PACK_FOLDER / GRAPHICS_FOLDER
    name, command = (None, None) if getattr(arguments, "no_png", False) else converter()
    png_note = ""
    font_notes = []
    families = installed_fonts() if name else None
    missing_fonts = sorted({graphic.font for graphic in graphics
                            if families is not None and graphic.font.lower() not in families})
    written = []
    with project.lock():
        output.mkdir(parents=True, exist_ok=True)
        for graphic in graphics:
            for orientation, file_name in graphic.file_names().items():
                svg_path = output / file_name
                svg_path.write_text(graphic.svg(mirrored=orientation == "mirrored"), encoding="utf-8")
                written.append(svg_path)
                if command is not None:
                    png_path = svg_path.with_suffix(".png")
                    try:
                        result = subprocess.run(command(svg_path, png_path), capture_output=True, text=True, timeout=120)
                        if result.returncode == 0 and png_path.is_file():
                            graphic.png_made = True
                            written.append(png_path)
                        else:
                            graphic.notes.append(f"the PNG of {file_name} could not be made ({name} stopped); the SVG is the graphic")
                    except (OSError, subprocess.SubprocessError):
                        graphic.notes.append(f"the PNG of {file_name} could not be made; the SVG is the graphic")
        if getattr(arguments, "no_png", False):
            png_note = "Only SVG files were written (--no-png)."
        elif command is None:
            png_note = ("No SVG converter is installed, so only SVG files were written. To make PNG copies, install "
                        "resvg or rsvg-convert and run the graphics command again, or open each SVG in a browser.")
        if missing_fonts:
            font_notes.append("The PNG copies were made without " + ", ".join(missing_fonts) + " installed, so they use "
                              "a stand-in font: install the fonts above and run the graphics command again before "
                              "they are used.")
        page = output / PAGE_NAME
        page.write_text(graphics_page(breakdown, graphics, settings, png_note, font_notes), encoding="utf-8")
        try:
            project.add_log_entry(f"Drew the text graphics: {len(graphics)} text{'s' if len(graphics) != 1 else ''} in picture.")
        except (OSError, ValueError):
            pass
    too_short = []
    for graphic in graphics:
        mirrored = " and mirrored" if graphic.mirrorable else " (never mirrored)"
        context.say(f"{graphic.title}: \"{graphic.words}\", drawn normal{mirrored}"
                    + (", with PNG copies." if graphic.png_made else "."))
        for shot, orientation, on_screen, seconds, _ in graphic.shots:
            if on_screen + 1e-9 < seconds and graphic.method != "background_blur":
                too_short.append(f"  Shot {three_digits(shot.identifier)} of {scene_label(breakdown, shot.identifier.split('-')[0])} "
                                 f"shows \"{graphic.words}\" {orientation} for {seconds_words(on_screen)}; reading it needs "
                                 f"{seconds_words(seconds)}.")
    for line in too_short:
        context.say(line)
    if png_note:
        context.say(png_note)
    for note in font_notes:
        context.say(note)
    context.say(f"Written: {PACK_FOLDER}/{GRAPHICS_FOLDER}/ ({len(written)} file{'s' if len(written) != 1 else ''} "
                f"and {PAGE_NAME})")
    context.summary = f"graphics: {len(graphics)} texts, {len(written)} files"
    return 1 if too_short else 0


def register_commands(table):
    table.add("graphics", "Draw the text graphics of every text in picture (SVG, normal and mirrored)", run_graphics,
              add_graphics_arguments)
